// app/resources/reactjs/components/Welcome.js
import React, {Component} from 'react';

export default class Welcome extends Component {
  render() {
      return (
          <div className="container">
              <div className="row">
                  <div className="col-md-8 col-md-offset-2">
                      <div className="panel panel-default">
                          <div className="panel-heading">Hello, World</div>

                          <div className="panel-body">
                              I am an example react component!
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      );
  }
}

// app/resources/vuejs/views/welcome/index.vue
<template>
  <div>
    <TopBanner/>
    <div class="container">
      <div class="row">
          <div class="col-md-8 col-md-offset-2">
              <div class="panel panel-default">
                  <div class="panel-heading">{{ head }}</div>

                  <div class="panel-body">
                    {{ body }}
                    <router-link to="/home">Go To Home</router-link>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>
</template>
<script>
import {TopBanner} from '@/components/'
export default {
  name: 'welcome',
  components: {
    TopBanner
  },
  data () {
    return {
      head: 'Hello, World',
      body: 'I am an example vuejs component!'
    }
  }
}
</script>
